M48
; DRILL file {KiCad 7.0.11-rc3} date Tue Mar 25 15:55:59 2025
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-25T15:55:59+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11-rc3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T2
X1.7Y-1.5
X1.7Y-2.4409
X2.9134Y-1.5
X2.9134Y-2.4409
T1
G00X3.0167Y-1.8877
M15
G01X3.0167Y-1.8563
M16
G05
M30
